# -*- coding: utf-8 -*-
"""community detection
## changed##
Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tg1SARXY8eusHCN51HKqn_V0nDS8E1bJ
"""

# Commented out IPython magic to ensure Python compatibility.
## off from https://www.analyticsvidhya.com/blog/2020/04/community-detection-graphs-networks/
import networkx as nx
import matplotlib.pyplot as plt

# %matplotlib inline

# load the graph
G = nx.karate_club_graph()
nx.draw(G, with_labels = True)

len(G.nodes), len(G.edges)

def edge_to_remove(graph):
  G_dict = nx.edge_betweenness_centrality(graph)
  edge = ()

  # extract the edge with highest edge betweenness centrality score
  for key, value in sorted(G_dict.items(), key=lambda item: item[1], reverse = True):
      edge = key
      break

  return edge

def girvan_newman(graph):
	# find number of connected components
	sg = nx.connected_components(graph)
	sg_count = nx.number_connected_components(graph)

	while(sg_count == 1):
		graph.remove_edge(edge_to_remove(graph)[0], edge_to_remove(graph)[1])
		sg = nx.connected_components(graph)
		sg_count = nx.number_connected_components(graph)

	return sg

# find communities in the graph
c = girvan_newman(G.copy())

# find the nodes forming the communities
node_groups = []

for i in c:
  node_groups.append(list(i))

node_groups

# plot the communities
color_map = []
for node in G:
    if node in node_groups[0]:
        color_map.append('blue')
    else:
        color_map.append('green')

nx.draw(G, node_color=color_map, with_labels=True)
plt.show()

G = nx.fast_gnp_random_graph(50, 0.05, seed=13, directed=False)

nx.draw(G, with_labels = True)

# find communities in the graph
c = girvan_newman(G.copy())

# find the nodes forming the communities
node_groups = []

for i in c:
  node_groups.append(list(i))

# plot the communities
color_map = []
for node in G:
    if node in node_groups[0]:
        color_map.append('blue')
    else:
        color_map.append('green')

nx.draw(G, node_color=color_map, with_labels=True)
plt.show()



"""louvain"""

pip install community

pip install python-louvain

pip uninstall community
Y

pip install python-louvain

import community.community_louvain as cl
import matplotlib.cm as cm
import matplotlib.pyplot as plt
import networkx as nx

# load the karate club graph
G = nx.karate_club_graph()
G = nx.fast_gnp_random_graph(50, 0.05, seed=13, directed=False)

#first compute the best partition
partition = cl.best_partition(G)

# draw the graph
pos = nx.spring_layout(G)
# color the nodes according to their partition
cmap = cm.get_cmap('viridis', max(partition.values()) + 1)
nx.draw_networkx_nodes(G, pos, partition.keys(), node_size=40,
                       cmap=cmap, node_color=list(partition.values()))
nx.draw_networkx_edges(G, pos, alpha=0.5)
plt.show()

